### ISSUE TITLE
website not working on both http and https when this plugin is enabled

### ISSUE THREAD

**Issue by santo74** [impresspages-plugins/SimpleCache#2]
When this plugin is enabled, the website does only work either via http or https but not both.

E.g. if I deploy the site and go to http://<my-site-url> everything is ok, but when I then go to the https version of the same url, I get cross domain issues.
The reason is that the plugin returns the cached page from the "http" location with all resources obviously still referring to http as well.

The solution would be that the plugin looks at the protocol of the request and cache different versions for the different protocols.

**Comment by maskas** [comment]
Does this fix helps?

https://github.com/impresspages-plugins/SimpleCache/commit/d419c242971198d77e2fd92cc31b6366cff84537

**Comment by santo74** [comment]
Yes, that seems to fix the issue.
Thanks!

One remark though: shouldn't the condition be the other way around?

```php
empty($_SERVER['HTTPS']) ? 'http://' : 'https://'
```
instead of
```php
empty($_SERVER['HTTPS']) ? 'https://' : 'http://'
```

**Comment by maskas** [comment]
Yes. You are right: https://github.com/impresspages-plugins/SimpleCache/commit/fac461dbb903d69043adb3fd836b06803562c2ca
